// HEADER
export const SET_HEADER_LINKS = 'SET_HEADER_LINKS';
export const SET_NAVBAR_LINKS = 'SET_NAVBAR_LINKS';
export const CHANGE_NAVBAR_ACTIVE = 'CHANGE_NAVBAR_ACTIVE';

// USER
export const SET_USER_PURCHASES = 'SET_USER_PURCHASES'; 
export const SET_PURCHASE_DETAIL = 'SET_PURCHASE_DETAIL';
