// HEADER
export const SET_HEADER_LINKS = 'SET_HEADER_LINKS';
export const SET_NAVBAR_LINKS = 'SET_NAVBAR_LINKS';
export const CHANGE_NAVBAR_ACTIVE = 'CHANGE_NAVBAR_ACTIVE';

// USER
export const SET_USER_PURCHASES = 'SET_USER_PURCHASES';
export const SET_PURCHASE_DETAIL = 'SET_PURCHASE_DETAIL';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

// USER CART
export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS';
export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT';

// SHOP
export const SET_SHOP_CATEGORIES = 'SET_SHOP_CATEGORIES';
export const SET_SHOP_PRODUCTS = 'SET_SHOP_PRODUCTS';
export const FILTER_PRODUCTS_WITH_CATEGORY_ID = 'FILTER_PRODUCTS_WITH_CATEGORY_ID';
export const FILTER_PRODUCTS_WITH_QUERY = 'FILTER_PRODUCTS_WITH_QUERY';